// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCc-117vX-crCkC361DVfsgt7SEXHSkNUw',
    appId: '1:1092342130740:web:ccbf58dd589991a9ff8261',
    messagingSenderId: '1092342130740',
    projectId: 'solar-4383c',
    authDomain: 'solar-4383c.firebaseapp.com',
    databaseURL: 'https://solar-4383c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-4383c.appspot.com',
    measurementId: 'G-S4V1PPHFV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwBVJm8-afadipmcILpXG0Pbr7Sr6Ej6I',
    appId: '1:1092342130740:android:e6a143295ffee5c6ff8261',
    messagingSenderId: '1092342130740',
    projectId: 'solar-4383c',
    databaseURL: 'https://solar-4383c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-4383c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxmQ9C6fFd0gxwk2YWxknYzY3_VAHx5-c',
    appId: '1:1092342130740:ios:97888505da1d5dadff8261',
    messagingSenderId: '1092342130740',
    projectId: 'solar-4383c',
    databaseURL: 'https://solar-4383c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-4383c.appspot.com',
    iosClientId: '1092342130740-sj5i3he7q3tan2v5vp96c8plblfaa4dd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSolarMp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxmQ9C6fFd0gxwk2YWxknYzY3_VAHx5-c',
    appId: '1:1092342130740:ios:3a6bf09374c0c4f2ff8261',
    messagingSenderId: '1092342130740',
    projectId: 'solar-4383c',
    databaseURL: 'https://solar-4383c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'solar-4383c.appspot.com',
    iosClientId: '1092342130740-gu09t0mkgvqafgl7qru7r4bc69a07rqo.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileSolarMp.RunnerTests',
  );
}
